---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prediction-consumer
  name: prediction-consumer
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction-consumer
