---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: throttling-observer-service
  name: throttling-observer-service
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: External
      external:
        metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: throttling-observer-service
