apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prediction-api
    component: image
  name: prediction-api
spec:
  # replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
        component: image
    spec:
      volumes:
        - name: consul-secret-reader
          secret:
            secretName: consul-secret-reader
      imagePullSecrets:
      - name: gcr-docker-cfg-eu
      containers:
      - name: prediction-api
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "--key-file=/etc/secrets/vault-manager/secret-reader.json", "-o", "nonempty", "#TODO", "/etc/secrets/consul"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/etc/secrets/consul"]
        image: eu.gcr.io/dev-lukas/prediction-api
        imagePullPolicy: IfNotPresent
        command:
          - /app/entrypoint.sh
        ports:
          - name: rest-api
            containerPort: 5000
        envFrom:
          - configMapRef:
              name: prediction-api-config
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
          - name: consul-secret-reader
            mountPath: /etc/secrets/vault-manager
