apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prediction-api
  name: prediction-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction-api
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
