apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boneseg-app-service
    component: image
  name: boneseg-app-service
spec:
  # replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: boneseg-app-service
  template:
    metadata:
      labels:
        app: boneseg-app-service
        component: image
    spec:
      volumes:
        - name: consul-secret-reader
          secret:
            secretName: consul-secret-reader
      imagePullSecrets:
      - name: gcr-docker-cfg-eu
      containers:
      - name: boneseg-app-service
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "--key-file=/etc/secrets/vault-manager/secret-reader.json", "-o", "nonempty", "$(CONSUL_SECRET_BUCKET)", "/etc/secrets/consul"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/etc/secrets/consul"]
        image: eu.gcr.io/dev-lukas/boneseg-postprocessing-service
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: boneseg-app-config
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
          - name: consul-secret-reader
            mountPath: /etc/secrets/vault-manager
