apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

bases:
  - ../../docker/base
  - ../../model-serving/base/versions/overlays

resources:
  - ./namespace.yaml
  - ./observer-deployment.yaml
  - ./boneseg-deployment.yaml
  - ./prediction-deployment.yaml
  - ./throttler-observer-deployment.yaml

configMapGenerator:
  - name: status-observer-config
    env: observer.env
  - name: throttler-observer-config
    env: throttler-observer.env
  - name: boneseg-app-config
    env: boneseg.env
  - name: prediction-consumer-config
    env: prediction.env

images:
  # status observer
  - name: eu.gcr.io/dev-lukas/status-observer-service
    newName: eu.gcr.io/dev-lukas/image-services-observer
  # prediction gateway
  - name: eu.gcr.io/dev-lukas/prediction-consumer-service
    newName: eu.gcr.io/dev-lukas/image-services-prediction
  # prediction post-processing
  - name: eu.gcr.io/dev-lukas/boneseg-postprocessing-service
    newName: eu.gcr.io/dev-lukas/image-services-boneseg
  - name: eu.gcr.io/dev-lukas/throttler-service
    newName: eu.gcr.io/dev-lukas/image-services-throttler

